### ISSUE TITLE
Fix CircleCi builds

### ISSUE THREAD

**Issue by FieryCod** [FieryCod/holy-lambda#12]
Tests are randomly failing from time to time:
https://circleci.com/gh/FieryCod/holy-lambda/384

**Comment by vemv** [comment]
Hey there,

the test is failing due to ordering issues:

![image](https://user-images.githubusercontent.com/1162994/63237490-90886a00-c242-11e9-85b3-a6bf366b0c21.png)

One possible fix would be to change the sorting criterion in https://github.com/FieryCod/holy-lambda/blob/e0bebef9cd9ca10c8fd8d338e0935f60acf751a4/src/clj/fierycod/holy_lambda/impl/agent.clj#L19 from `:name` to `:path`, since from what I can see, `:name` is not a unique criterion.

Cheers - V

**Comment by FieryCod** [comment]
Hi @vemv, 
Thank you for your comment. That is certainly it.
Are you interested in providing a PR?

**Comment by vemv** [comment]
Not needed, I'm happy to have just helped!
