### ISSUE TITLE
[FEATURE] CDK support

### ISSUE THREAD

**Issue by eoliphan** [FieryCod/holy-lambda#57]
Would be nice to integrate with CDK projects, use holy-lambda for clojure goodness in lambdas, CDK  to glue together larger app.  There's beta SAM/CDK support [here](https://aws.amazon.com/blogs/compute/better-together-aws-sam-and-aws-cdk/)

**Comment by FieryCod** [comment]
@eoliphan HL can be easily integrated with CDK projects. 

AWS SAM is used in HL only for deployment since AWS SAM does not know how to build the deployable artifacts (HL does).

Depending on the runtime HL spits artifact to different location at `.holy-lambda` which you can easily find ;)

**Artifact build depending on the runtime**
- Java runtime (only java8) (bb stack:compile) the result is a .jar 
- Babashka runtime (sources are provided as is). Pack `/src` to a zip and reference the ARN of the runtime. Additional packages like pods, or Clojure deps are downloaded to either `.holy-lambda/pods` or `.holy-lambda/.m2`
- Native runtime which produces a zip via `bb native:executable`. Artifact might be found (AFAIK since I'm on phone) at `.holy-lambda/native/latest.zip`.

I think in that situation you can first experiment with HL and CDK and report back what you're missing. I'm eager to make CDK integration with HL easier if I know what is important for you and the users.

**Comment by eoliphan** [comment]
Ok great info, just started playing around with holy-lambda, so will update this as stuff comes up

**Comment by FieryCod** [comment]
@eoliphan Any progress? :)

**Comment by FieryCod** [comment]
@eoliphan Here is the working example: https://github.com/FieryCod/holy-lambda-azure-cdk-deployment

**Comment by FieryCod** [comment]
holy-lambda for the long time works with any deployment tool. Pulumi, Terraform, CDK, AWS SAM you name it. This template is very old and uses the deprecated API. I would encourage you to create a new project via holy-lambda template using clj-new and then transform what is inside AWS SAM template.yml to CDK.
